spring:
  application:
    name: social-media

  datasource:
    url: jdbc:mysql://rev-project-2-database.cpy400ikce24.us-east-2.rds.amazonaws.com:3306/rev_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: kammYv-8xapja-tapdij

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
